
### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/single:start-now

### Starts workflow now.
POST {{host}}{{profiles.two}}/workflows/slow-duo:start-now

> {%


    client.test("Workflow scheduled successfully.", function() {
        client.assert(response.status === 202, "Expected status 202 Accepted.");
        client.assert(response.body, "Response should have a body.");
        client.assert(response.body.next, "Response should contain next execution time");
        console.log("Workflow scheduled for:", response.body.next);
    });


%}

### Starts workflow now.
POST {{host}}{{profiles.two}}/fast-trio:start-now

### Start a workflow now only once; 202 Accepted
POST {{host}}{{profiles.two}}/variable-flood:start-now

### Starts workflow now but it times out.
POST {{host}}{{profiles.two}}/times-out:start-now

### Starts workflow with a delay once.
POST {{host}}{{profiles.one}}/single:start-in
Content-Type: application/json

{ "wait": "00:00:15" }



### Starts workflow at the specified time.
POST {{host}}{{profiles.one}}/single:start-at
Content-Type: application/json

{
    "when": "2025-07-15T10:05Z"
}
