@host=http://localhost:5049
@offline={{host}}/api/jobs/Offline

### Fetch all offline workflows as yaml.
GET {{offline}}
Accept: application/json

### Fetch the one with invalid cron.
GET {{offline}}?q=invalid.cron-too-long
Accept: application/json

### Fetch all offline workflows as json.
GET {{offline}}
Accept: application/json

### Fetch workflow by filter.
GET {{offline}}?q=use-all-vars
Accept: application/json

### Does not find an enabled workflows.
GET {{offline}}?q=say-hallo
Accept: application/json

### Does not find a fake workflow.
GET {{offline}}?q=fake
Accept: application/json

### Fetch workflows that start with "run-".
GET {{offline}}?q=run-*
Accept: application/json

### Start a workflow now.
POST {{offline}}/say-hallo/start
Accept: application/json

### Start a workflow in 10 seconds.
POST {{offline}}/say-hallo/start/10
Accept: application/json

### Start a workflow.
POST {{offline}}/has-no-steps/start
Accept: application/json

### Fails to start the workflow due to missing env-var.
POST {{offline}}/invalid.env-var-missing/start
Accept: application/json