@host=http://localhost:5049
@pending={{host}}/api/jobs/Pending

### Fetch all pending workflows.
GET {{pending}}
Accept: application/json

### GET requect for a single offline workflow that exists
GET http://localhost:5049/api/jobs/Offline/foo
Accept: application/json

### GET requect for a single offline workflow that does not exist
GET http://localhost:5049/api/jobs/Pending/
Accept: application/json

### POST
POST http://localhost:5049/api/jobs/Pending/foo/start/now
Accept: application/json

### POST
POST http://localhost:5049/api/jobs/Pending/foo/start/later/30
Accept: application/json


### POST
POST {{pending}}/sync
Accept: application/json

