@host=http://localhost:5049
@maintenance={{host}}/api/profiles/main/maintenance


### Lists maintenance locks.
POST {{host}}{{profiles.two}}/downtimes:end
Content-Type: application/json

{
    "filter": "single"
}