
### Starts maintenance relative from now.
POST {{host}}{{profiles.two}}/downtimes:start-in
Content-Type: application/json

{
    "filter": "single",
    "wait": "00:00:05",
    "duration": "00:30:00"
}

### Starts maintenance at the specified time.
POST {{host}}{{profiles.two}}/downtimes:startAt
Content-Type: application/json

{
    "filter": "*",
    "from": "2025-07-01T22:00Z",
    "to": "2025-07-01T23:00Z"
}
