
### Starts workflow now.
POST {{host}}{{profiles.one}}/says-hallo:start-now

> {%
    client.test("Workflow scheduled successfully.", function() {
        client.assert(response.status === 202, "Expected status 202 Accepted.");
        client.assert(response.body, "Response should have a body.");
        client.assert(response.body.next, "Response should contain next execution time");
        console.log("Workflow scheduled for:", response.body.next);
    });
%}


### Starts workflow now but it times out.
POST {{host}}{{profiles.one}}/times-out:start-now

### Start a workflow now only once; 202 Accepted
POST {{host}}{{profiles.one}}/uses-all-vars:start-now


### Starts workflow with a delay once.
POST {{host}}{{profiles.one}}/says-hallo:start-in
Content-Type: application/json

{ "wait": "00:00:15" }



### Starts workflow at the specified time.
POST {{host}}{{profiles.one}}/says-hallo:start-at
Content-Type: application/json

{
    "when": "2025-07-15T10:05Z"
}

### Fauks to start workflow that does not exist.
POST {{host}}{{profiles.one}}/says-hallo-2:startAt
Content-Type: application/json

{
    "when": "2020-07-01T22:00Z"
}
