@host=http://localhost:5049
@offline={{host}}/api/jobs/Offline

### Fetch all active maintenance tokens; 200 OK
GET /api/maintenance?q={filter}&orderBy=createdOn&orderBy=expiresIn

### Start maintenance relative from now; 201 Created or an error when period in the past; include location header pointing to the new location
POST /api/maintenance/{name}:startIn
Content-Type: application/json

{
    "wait": "00:00:05",
    "duration": "00:20:00",
    "reason": "test"
}

### Start maintenance at the specified time.
POST /api/maintenance/{name}:startAt
Content-Type: application/json

{
    "from": "2025-07-01T22:00Z",
    "to": "2025-07-01T23:00Z",
    "reason": "test"
}

### End maintenance before it expires; 204 No Content
DELETE /api/maintenance/{name}
Content-Type: application/json
