
### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/fast-trio:start-now

### Starts workflow at the specified time.
POST {{host}}{{profiles.hallo}}/workflows/hallo-npc-lite:start-now

### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/hallo-1-of-3:start-now

### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/hallo-cmd:start-now

### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/hallo-pwsh:start-now

### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/hallo-variables:start-now


### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/hallo-npc:start-now
Content-Type: application/json

{
  "steps": []
}

### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows/fast-trio:start-now
Content-Type: application/json

{
  "steps": [1, "foo"]
}

### Starts workflow at the specified time.
POST {{host}}{{profiles.two}}/workflows:sync

