

### Starts the workflow now.
POST {{host}}{{profiles.hallo}}/workflows/hallo-npc-lite:start-now

### Starts the workflow now.
POST {{host}}{{profiles.hallo}}/workflows/hallo-npc-full:start-now

### Starts the workflow now but only selected steps.
POST {{host}}{{profiles.hallo}}/workflows/hallo-npc-full:start-now
Content-Type: application/json

{
  "steps": [
    1
  ]
}

### Starts the workflow now.
POST {{host}}{{profiles.hallo}}/workflows/hallo-cmd:start-now

### Starts the workflow now.
POST {{host}}{{profiles.hallo}}/workflows/hallo-pwsh:start-now

### Synchronizes the profile.
POST {{host}}{{profiles.hallo}}/workflows:sync

